merge_derives = true
fn_params_layout = "Compressed"
tab_spaces = 4
reorder_imports = true
unstable_features = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
brace_style = "PreferSameLine"
wrap_comments = true
condense_wildcard_suffixes = true
hex_literal_case = "Upper"
enum_discrim_align_threshold = 20